baseline:
  name: truth
cycles:
  start: 2024-04-01T02:00:00
  step: 1
  stop: 2024-04-07T23:00:00
forecast:
  coords:
    latitude: latitude
    level: level
    longitude: longitude
    time:
      inittime: time
      leadtime: lead_time
  mask:
    - [52.61564933, 225.90452027]
    - [52.61564933, 255.00000000]
    - [21.138123,   255.00000000]
    - [21.138123,   225.90452027]
  name: AIWX
  path: /path/to/forecast.zarr
  projection:
    a: 6371229
    b: 6371229
    lat_0: 38.5
    lat_1: 38.5
    lat_2: 38.5
    lon_0: 262.5
    proj: lcc
leadtimes: 
  start: "01:00:00"
  step: "01:00:00"
  stop: "24:00:00"
meta:
  grids: "{{ meta.workdir }}/grids"
  levels: &levels [200, 300, 475, 800, 825, 850, 875, 900, 925, 950, 975, 1000]
  workdir: /path/to/workdir
paths:
  grids:
    forecast: "{{ meta.grids }}/forecast"
    truth: "{{ meta.grids }}/truth"
  run: "{{ meta.workdir }}/run"
regrid:
  method: NEAREST
  to: forecast
truth:
  name: HRRR
  type: grid
  url: https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.{{ yyyymmdd }}/conus/hrrr.t{{ hh }}z.wrfprsf{{ "%02d" % fh }}.grib2
variables:
  HGT:
    level_type: isobaricInhPa
    levels: *levels
    name: gh
  PRES:
    level_type: surface
    name: sp
  REFC:
    level_type: atmosphere
    name: refc
  SPFH:
    level_type: isobaricInhPa
    levels: *levels
    name: q
  T2M:
    level_type: heightAboveGround
    levels: [2]
    name: 2t
  TMP:
    level_type: isobaricInhPa
    levels: *levels
    name: t
  UGRD:
    level_type: isobaricInhPa
    levels: *levels
    name: u
  UGRD10:
    level_type: heightAboveGround
    levels: *levels
    name: u_10m
  VGRD:
    level_type: isobaricInhPa
    levels: *levels
    name: v
  VGRD10:
    level_type: heightAboveGround
    levels: *levels
    name: v_10m
  VVEL:
    level_type: isobaricInhPa
    levels: *levels
    name: w
