baseline:
  compare: false
  name: PREPBUFR
  type: point
  url: https://noaa-reanalyses-pds.s3.amazonaws.com/observations/reanalysis/conv/prepbufr/{{ yyyymmdd[:4] }}/{{ yyyymmdd[4:6] }}/prepbufr/gdas.{{ yyyymmdd }}.t{{ hh }}z.prepbufr.nr
cycles:
  - 2022-02-01T12:00:00
forecast:
  coords:
    latitude: latitude
    level: level
    longitude: longitude
    time:
      inittime: forecast_reference_time
      validtime: time
  name: AIWX
  path: /path/to/forecast.zarr
  projection:
    proj: latlon
leadtimes: [0, 6, 12, 18]
meta:
  grids: "{{ meta.workdir }}/grids"
  workdir: /path/to/workdir
paths:
  grids:
    forecast: "{{ meta.grids }}/forecast"
  obs: "{{ meta.workdir }}/obs"
  run: "{{ meta.workdir }}/run"
regrid:
  method: BILIN
  to: G104
variables:
  10m_u_component_of_wind:
    level_type: heightAboveGround
    levels: [10]
    name: u_10m
  10m_v_component_of_wind:
    level_type: heightAboveGround
    levels: [10]
    name: v_10m
  2m_temperature:
    level_type: heightAboveGround
    levels: [2]
    name: 2t
  geopotential:
    level_type: isobaricInhPa
    levels: [500]
    name: gh
  surface_pressure:
    level_type: surface
    name: sp
  specific_humidity:
    level_type: isobaricInhPa
    levels: [850]
    name: q
  temperature:
    level_type: isobaricInhPa
    levels: [850]
    name: t
  u_component_of_wind:
    level_type: isobaricInhPa
    levels: [250]
    name: u
  v_component_of_wind:
    level_type: isobaricInhPa
    levels: [250]
    name: v
